env:
  browser: true
  commonjs: true
  es2021: true
parserOptions:
  ecmaVersion: 12
rules: {}
extends:
  - eslint:recommended
  - plugin:jest/style
  - plugin:jest/recommended
globals:
    mockRemoteServer: true
